### ISSUE TITLE
SetOutputSize dosent work in exsample

### ISSUE THREAD

**Issue by brogii** [Synthoid/UnitySubstanceExtensions#1]
can set all SubstanceGraph properties in code ?

**Comment by Synthoid** [comment]
I forgot to add a call to Substance.RenderSubstancesAsync() in the example scene. I have added that line and everything should now work as expected.

As for general property adjustments, you can use various calls like the following:

```
SubstanceGraph graph = substance.graphs[0];

graph.SetInputInt("paramName", value);
graph.SetInputColor("paramName", value);
```

**Comment by brogii** [comment]
> I forgot to add a call to Substance.RenderSubstancesAsync() in the example scene. I have added that line and everything should now work as expected.
> 
> As for general property adjustments, you can use various calls like the following:
> 
> ```
> SubstanceGraph graph = substance.graphs[0];
> 
> graph.SetInputInt("paramName", value);
> graph.SetInputColor("paramName", value);
> ```

where is Substance.RenderSubstancesAsync()  ?
i cant find this api
